# blocks.py generated by touch-torch.com
def unname(ctx):
    T.clickByImg(src="more.png", crop={"unit":"%","x":53,"y":0,"width":47,"height":32})
    T.sleep(1)
    T.clickByImg(src="more-fuben.png", crop={"unit":"%","x":42,"y":0,"width":58,"height":32})
    T.sleep(1)
    for count in range(4):
        T.clickByText(search="扫荡", crop={"unit":"%","x":13,"y":65,"width":55,"height":35})
        T.sleep(1)
        T.click(x=50, y=80, unit="%")
        T.sleep(1)
        T.click(x=50, y=80, unit="%")


T.jobRegister(unname, cronjob="*", enable=True)
